/* DEPLOY SCRIPT FOR EMOJI CLOUD DATABASE 
 * DROPS ALL TABLES AND DATABASES AND RECREATES THEM
 * IN ORDER TO CREATE A NEW INSTANCE OF THE DATABASE
 */

/* DROP TABLES FROM EMOJI_CLOUD */
DROP TABLE IF EXISTS EMOJI_CLOUD.TWEETS;
DROP TABLE IF EXISTS EMOJI_CLOUD.EMOJI;


/* DROP DATABASE */
DROP DATABASE EMOJI_CLOUD;
CREATE DATABASE EMOJI_CLOUD;


/* USE DATABASE */
USE EMOJI_CLOUD;

/* CHANGES THE DATABASE CHARACTER SET TO ALLOW FOR EMOJIS */
ALTER DATABASE EMOJI_CLOUD CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;


/* CREATES EMOJI TABLE
 * 		UNICODE_ID - UNICODE FOR A GIVEN EMOJI
 * 		EMOJI_NAME - NAME OF EMOJI
 * 		EMOJI_DESC - SHORT DESCRIPTION OF THE EMOJI
 * 		HTML_HEX_CODE - REPRESENTATION OF EMOJI FOR HTML
 * 		INSERT_DATETIME - TIMESTAMP OF WHEN THE EMOJI WAS FIRST INSERTED INTO THE DATABASE
 */
CREATE TABLE IF NOT EXISTS EMOJIS (
	UNICODE_ID VARCHAR(255) NOT NULL,
	EMOJI_NAME VARCHAR(255),
	EMOJI_DESC VARCHAR(255),
	HTML_HEX_CODE VARCHAR(255),
	INSERT_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (EMOJI_NAME)) ;


/* CREATES TWEETS TABLE
 * 		UNIQUE_ID (PRIMARY KEY) - ID THAT AUTOINCREMENTS ON INSERT
 * 		TWEET_ID - ID GIVEN FROM TWITTER (NOT UNIQUE)
 * 		TWEET_TEXT - FULL CONTENT OF THE TWEET
 * 		UNICODE_ID (FOREIGN KEY) - UNICODE_ID OF A SINGLE EMOJI (TWEETS WITH MULTIPLE EMOJIS GET PARSED)
 * 		TWEET_DATETIME - TIMESTAMP OF WHEN THE TWEET WAS CREATED (FROM TWITTER)
 */
CREATE TABLE IF NOT EXISTS TWEETS (
	UNIQUE_ID INT NOT NULL AUTO_INCREMENT UNIQUE,
	TWEET_ID VARCHAR(255) NOT NULL,
	TWEET_TEXT BLOB,
	EMOJI_NAME VARCHAR(255),
	TWEET_DATETIME TIMESTAMP,
	PRIMARY KEY (UNIQUE_ID),
	FOREIGN KEY (EMOJI_NAME) REFERENCES EMOJIS(EMOJI_NAME)
);