/* OTHER HELPFUL QUERYS FOR API, DEBUGGING AND DASHBOARDING
 * 
*/

/* GETS THE COUNTS FROM TABLES */
SELECT
	COUNT(*) AS EMOJI_COUNT,
	(
	SELECT
		COUNT(*)
	FROM
		EMOJI_CLOUD.TWEETS) AS TWEETS_COUNT
FROM
	EMOJI_CLOUD.EMOJIS;

/* GETS THE SIZE OF THE TABLES IN THE DATABASE */

SELECT
	table_name AS "Table",
	ROUND(((data_length + index_length) / 1024 / 1024), 2) AS "Size (MB)"
FROM
	information_schema.TABLES
WHERE
	table_schema = "database_name"
ORDER BY
	(data_length + index_length) DESC;
	
/* 
 * GET THE TOP 10 EMOJIS OF ALL TIME AND SHOW THE COUNT FROM LAST WEEK BY DAY
*/
SELECT
	E.UNICODE_ID,
	T.EMOJI_NAME,
	COUNT(*) AS TOTAL_ALL_TIME,
	SUM(CASE WHEN T.TWEET_DATETIME > NOW() - INTERVAL 1440 MINUTE THEN 1 ELSE 0 END) AS 'TODAY',
	SUM(CASE WHEN T.TWEET_DATETIME > NOW() - INTERVAL 2880 MINUTE AND T.TWEET_DATETIME < NOW() - INTERVAL 1440 MINUTE THEN 1 ELSE 0 END) AS 'YESTURDAY',
	SUM(CASE WHEN T.TWEET_DATETIME > NOW() - INTERVAL 4320 MINUTE AND T.TWEET_DATETIME < NOW() - INTERVAL 2880 MINUTE THEN 1 ELSE 0 END) AS '2 DAYS AGO',
	SUM(CASE WHEN T.TWEET_DATETIME > NOW() - INTERVAL 5760 MINUTE AND T.TWEET_DATETIME < NOW() - INTERVAL 4320 MINUTE THEN 1 ELSE 0 END) AS '3 DAYS AGO',
	SUM(CASE WHEN T.TWEET_DATETIME > NOW() - INTERVAL 7200 MINUTE AND T.TWEET_DATETIME < NOW() - INTERVAL 5760 MINUTE THEN 1 ELSE 0 END) AS '4 DAYS AGO',
	SUM(CASE WHEN T.TWEET_DATETIME > NOW() - INTERVAL 8640 MINUTE AND T.TWEET_DATETIME < NOW() - INTERVAL 7200 MINUTE THEN 1 ELSE 0 END) AS '5 DAYS AGO',
	SUM(CASE WHEN T.TWEET_DATETIME > NOW() - INTERVAL 10080 MINUTE AND T.TWEET_DATETIME < NOW() - INTERVAL 8640 MINUTE THEN 1 ELSE 0 END) AS '6 DAYS AGO',
	SUM(CASE WHEN T.TWEET_DATETIME > NOW() - INTERVAL 11520 MINUTE AND T.TWEET_DATETIME < NOW() - INTERVAL 10080 MINUTE THEN 1 ELSE 0 END) AS '7 DAYS AGO'
FROM
	EMOJI_CLOUD.TWEETS T
JOIN EMOJI_CLOUD.EMOJIS E ON
	T.EMOJI_NAME = E.EMOJI_NAME
GROUP BY
	E.UNICODE_ID,
	T.EMOJI_NAME
ORDER BY
	COUNT(*) DESC
LIMIT 10;

/*
 * GET THE TOP 25 EMOJIS FROM TODAY AND SHOW THE COUNT FROM LAST 1, 10, 60 AND 720 MINUTES
*/
SELECT
	E.UNICODE_ID,
	T.EMOJI_NAME,
	COUNT(*) AS 'TODAY',
	SUM(CASE WHEN T.TWEET_DATETIME > NOW() - INTERVAL 1 MINUTE THEN 1 ELSE 0 END) AS 'LAST 1 MINUTES',
	SUM(CASE WHEN T.TWEET_DATETIME > NOW() - INTERVAL 10 MINUTE THEN 1 ELSE 0 END) AS 'LAST 10 MINUTES',
	SUM(CASE WHEN T.TWEET_DATETIME > NOW() - INTERVAL 60 MINUTE THEN 1 ELSE 0 END) AS 'LAST 1 HOUR',
	SUM(CASE WHEN T.TWEET_DATETIME > NOW() - INTERVAL 720 MINUTE THEN 1 ELSE 0 END) AS 'LAST 12 HOURS'
FROM
	EMOJI_CLOUD.TWEETS T
JOIN EMOJI_CLOUD.EMOJIS E ON
	T.EMOJI_NAME = E.EMOJI_NAME
WHERE
	T.TWEET_DATETIME > NOW() - INTERVAL 1440 MINUTE
GROUP BY
	E.UNICODE_ID,
	T.EMOJI_NAME
ORDER BY
	COUNT(*) DESC
LIMIT 25;

/*
 * RETURNS THE EMOJI, EMOJI NAME, EMOJI DESCRIPTION, AND EMOJI COUNT
 * TOP 100 EMOJIS OF ALL TIME
 * ADD 'WHERE T.TWEET_DATETIME > NOW() - INTERVAL X MINUTE' TO LIMIT TIME RANGE
*/
SELECT
	E.UNICODE_ID AS 'EMOJI',
	T.EMOJI_NAME AS 'EMOJI NAME',
	E.EMOJI_DESC AS 'EMOJI DESCRIPTION',
	COUNT(*) AS 'EMOJI COUNT'
FROM
	EMOJI_CLOUD.EMOJIS E
JOIN EMOJI_CLOUD.TWEETS T ON
	E.EMOJI_NAME = T.EMOJI_NAME
GROUP BY
	T.EMOJI_NAME,
	E.EMOJI_DESC,
	E.HTML_HEX_CODE,
	E.UNICODE_ID
ORDER BY
	COUNT(*) DESC
LIMIT 100;